version = 1

exclude_patterns = [
  "node_modules/**",
  "frontend/node_modules/**",
  "dist/**",
  "build/**",
  ".venv/**",
  "env/**",
  "__pycache__/**",
  "frontend/cypress/videos/**",
  "frontend/cypress/screenshots/**",
  "frontend/coverage/**",
]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.11"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "ruff"
