  5a26kq-codex/fix-incorrect-signage-in-transactions[m
  add-bar-click-event-handling-to-charts2025-06-28[m
  awd7x8-codex/remove-duplicate-style-block-from-updatetransactionstable.vu[m
  codex/add-modal-popup-for-chart-interaction[m
  codex/add-post-route-for-scanning-recurring-transactions[m
  codex/add-user-role-feature[m
  codex/fix-data-loading-issue-and-tolowercase-error[m
  codex/fix-incorrect-signage-in-transactions[m
  codex/fix-vue-warning-for-undefined-selectedtype[m
  codex/implement-and-update-forecast-functionality[m
  codex/integrate-forecastorchestrator-and-add-tests[m
  codex/modify-sync_to_db-and-add-unit-tests[m
  dwmzmj-codex/implement-and-update-forecast-functionality[m
  fix-account-snapshot-section2025-06-23[m
  id79wg-codex/implement-and-update-forecast-functionality[m
* [32minvestigate-transactions-table-loading-issue2025-06-28[m
  jrdnj5-codex/integrate-dark-frost--neon-accent-theme[m
  ketx96-codex/add-user-role-feature[m
  khgz1l-codex/fix-vue-warning-for-undefined-selectedtype[m
  l360tq-codex/implement-and-update-forecast-functionality[m
  main[m
  mvea6b-codex/add-user-role-feature[m
  p5eu6g-codex/implement-and-update-forecast-functionality[m
  q2cnfg-codex/fix-vue-warning-for-undefined-selectedtype[m
  refactor-categorybreakdownchart-to-use-categorymenutree2025-06-28[m
  replace-sumamounts-with-root-level-sum-function2025-06-28[m
  siae90-codex/add-account-hide-feature[m
  update-files-with-reference-to-main.css2025-06-27[m
  update-paths-and-add-note-in-tailwind_vite_style_reference.m2025-06-27[m
  vegs3x-codex/add-account-hide-feature[m
  w0lwmp-codex/integrate-forecastorchestrator-and-add-tests[m
  xdzjau-codex/add-post-route-for-scanning-recurring-transactions[m
  xueqci-add-bar-click-event-handling-to-charts2025-06-28[m
