services:
  - type: web
    name: pynance-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "backend.run:app" --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: BACKEND_PUBLIC_URL
        value: https://your-worker.example
    buildFilter:
      paths:
        - backend/**

  - type: web
    name: pynance-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: npm run preview
    staticPublishPath: frontend/dist
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
