from flask import Blueprint, jsonify, request

from app.extensions import db
from app.services.forecast_orchestrator import ForecastOrchestrator

forecast = Blueprint("forecast", __name__)


@forecast.route("", methods=["GET"])
def get_forecast():
    """Return forecast payload generated by :class:`ForecastOrchestrator`."""
    try:
        view_type = request.args.get("view_type", "Month")
        manual_income = float(request.args.get("manual_income", 0))
        liability_rate = float(request.args.get("liability_rate", 0))

        orchestrator = ForecastOrchestrator(db.session)
        payload = orchestrator.build_forecast_payload(
            user_id=request.args.get("user_id"),
            view_type=view_type,
            manual_income=manual_income,
            liability_rate=liability_rate,
        )
        return jsonify(payload), 200
    except Exception as e:  # pragma: no cover - defensive
        return jsonify({"error": str(e)}), 500
