"""empty message

Revision ID: 86fc66ae2627
Revises: c5669e264520
Create Date: 2025-08-15 15:17:27.518586

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86fc66ae2627"
down_revision = "c5669e264520"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("target_amount", sa.Float(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financial_goals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_financial_goals_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_financial_goals_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_internal", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("internal_match_id", sa.String(length=64), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_is_internal"), ["is_internal"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_is_internal"))
        batch_op.drop_column("internal_match_id")
        batch_op.drop_column("is_internal")

    with op.batch_alter_table("financial_goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_goals_user_id"))
        batch_op.drop_index(batch_op.f("ix_financial_goals_account_id"))

    op.drop_table("financial_goals")
    # ### end Alembic commands ###
