"""I think migration

Revision ID: c5669e264520
Revises: 40b08ff58897
Create Date: 2025-07-23 10:33:10.733460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5669e264520'
down_revision = '40b08ff58897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    plaid_columns = {col["name"] for col in insp.get_columns('plaid_accounts')}

    with op.batch_alter_table('plaid_accounts', schema=None) as batch_op:
        if 'product' not in plaid_columns:
            batch_op.add_column(sa.Column('product', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_accounts', schema=None) as batch_op:
        batch_op.drop_column('product')

    # ### end Alembic commands ###
