"""Balance back in Accounts table

Revision ID: 704d1b24f7a6
Revises: 0ee5338170fd
Create Date: 2025-04-24 21:51:44.505926

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "704d1b24f7a6"
down_revision = "0ee5338170fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("balance", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("balance")

    # ### end Alembic commands ###
