/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountsReorderChart: typeof import('./components/AccountsReorderChart.vue')['default']
    AccountsTable: typeof import('./components/AccountsTable.vue')['default']
    AccountsTableLite: typeof import('./components/AccountsTableLite.vue')['default']
    AssetsBarTrended: typeof import('./components/AssetsBarTrended.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CardContent: typeof import('./components/ui/CardContent.vue')['default']
    CategoryBreakdownChart: typeof import('./components/CategoryBreakdownChart.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    DailyNetChart: typeof import('./components/DailyNetChart.vue')['default']
    DownloadCSV: typeof import('./components/DownloadCSV.vue')['default']
    ForecastAdjustmentsForm: typeof import('./components/forecast/ForecastAdjustmentsForm.vue')['default']
    ForecastBreakdown: typeof import('./components/forecast/ForecastBreakdown.vue')['default']
    ForecastChart: typeof import('./components/forecast/ForecastChart.vue')['default']
    ForecastComponent: typeof import('./components/forecast/ForecastComponent.vue')['default']
    ForecastLayout: typeof import('./components/forecast/ForecastLayout.vue')['default']
    ForecastSummaryPanel: typeof import('./components/forecast/ForecastSummaryPanel.vue')['default']
    ImportFileSelector: typeof import('./components/ImportFileSelector.vue')['default']
    LinkAccount: typeof import('./components/LinkAccount.vue')['default']
    LinkAccountFullProducts: typeof import('./components/LinkAccountFullProducts.vue')['default']
    LinkProviderLauncher: typeof import('./components/LinkProviderLauncher.vue')['default']
    ManualTransactionsTable: typeof import('./components/ManualTransactionsTable.vue')['default']
    ManualTransactionTable: typeof import('./components/ManualTransactionTable.vue')['default']
    MatchingTransactionUpload: typeof import('./components/MatchingTransactionUpload.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NetIncomeCharts: typeof import('./components/NetIncomeCharts.vue')['default']
    NetYearComparisonChart: typeof import('./components/NetYearComparisonChart.vue')['default']
    NewNavbarDev: typeof import('./components/NewNavbar-Dev.vue')['default']
    NotificationsBar: typeof import('./components/recurring/NotificationsBar.vue')['default']
    PlaidProductScopeSelector: typeof import('./components/PlaidProductScopeSelector.vue')['default']
    RecurringCalendar: typeof import('./components/RecurringCalendar.vue')['default']
    RecurringTransactionSection: typeof import('./components/recurring/RecurringTransactionSection.vue')['default']
    RefreshControls: typeof import('./components/RefreshControls.vue')['default']
    RefreshPlaidControls: typeof import('./components/RefreshPlaidControls.vue')['default']
    RefreshTellerControls: typeof import('./components/RefreshTellerControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
    TempForecast: typeof import('./components/TempForecast.vue')['default']
    TempRecoveredTokenUpload: typeof import('./components/TempRecoveredTokenUpload.vue')['default']
    Toast: typeof import('./components/base/Toast.vue')['default']
    TokenUpload: typeof import('./components/TokenUpload.vue')['default']
    TransactionsTable: typeof import('./components/TransactionsTable.vue')['default']
    TransactionUploadCSV: typeof import('./components/TransactionUploadCSV.vue')['default']
    UpdateTransactionsTable: typeof import('./components/UpdateTransactionsTable.vue')['default']
    UploadCSV: typeof import('./components/UploadCSV.vue')['default']
    UploadDownloadCSV: typeof import('./components/UploadDownloadCSV.vue')['default']
    YoutubeEmbed: typeof import('./components/YoutubeEmbed.vue')['default']
  }
}
