/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountsReorderChart: typeof import('./components/AccountsReorderChart.vue')['default']
    AccountsTable: typeof import('./components/AccountsTable.vue')['default']
    AccountsTableLite: typeof import('./components/AccountsTableLite.vue')['default']
    AssetsBarTrended: typeof import('./components/AssetsBarTrended.vue')['default']
    CategoryBreakdownChart: typeof import('./components/CategoryBreakdownChart.vue')['default']
    Chart: typeof import('./components/Chart.vue')['default']
    DailyNetChart: typeof import('./components/DailyNetChart.vue')['default']
    DownloadCSV: typeof import('./components/DownloadCSV.vue')['default']
    LinkAccount: typeof import('./components/LinkAccount.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NetIncomeCharts: typeof import('./components/NetIncomeCharts.vue')['default']
    NetYearComparisonChart: typeof import('./components/NetYearComparisonChart.vue')['default']
    NewNavbarDev: typeof import('./components/NewNavbar-Dev.vue')['default']
    NotificationsBar: typeof import('./components/NotificationsBar.vue')['default']
    RecurringCalendar: typeof import('./components/RecurringCalendar.vue')['default']
    RecurringTransactionSection: typeof import('./components/RecurringTransactionSection.vue')['default']
    RefreshControls: typeof import('./components/RefreshControls.vue')['default']
    RefreshPlaidControls: typeof import('./components/RefreshPlaidControls.vue')['default']
    RefreshTellerControls: typeof import('./components/RefreshTellerControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
    TokenUpload: typeof import('./components/TokenUpload.vue')['default']
    TransactionsTable: typeof import('./components/TransactionsTable.vue')['default']
    UpdateTransactionsTable: typeof import('./components/UpdateTransactionsTable.vue')['default']
    UploadCSV: typeof import('./components/UploadCSV.vue')['default']
    UploadDownloadCSV: typeof import('./components/UploadDownloadCSV.vue')['default']
    YoutubeEmbed: typeof import('./components/YoutubeEmbed.vue')['default']
  }
}
