"""empty message

Revision ID: 027941158fbe
Revises: 2c4d6e8f9a10
Create Date: 2026-04-25 04:19:40.066023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027941158fbe'
down_revision = '2c4d6e8f9a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('account_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_history_account_date'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_category_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_user_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_user_date'), ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category_date'), ['category_id', 'date'], unique=False)

    with op.batch_alter_table('account_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_history_account_date'), ['account_id', 'date'], unique=False)

    with op.batch_alter_table('account_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
