"""Add fucking pending check wtf plaid

Revision ID: 1a013aa715bd
Revises: a5b61ca1f626
Create Date: 2025-04-30 01:28:52.642278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a013aa715bd'
down_revision = 'a5b61ca1f626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('pending')

    # ### end Alembic commands ###
