"""Added metadata table

Revision ID: 3434a52b5364
Revises: e78654fb895b
Create Date: 2025-07-05 17:30:43.278456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3434a52b5364'
down_revision = 'e78654fb895b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_id'), ['account_id'], unique=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pfc_primary', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pfc_detailed', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pfc_icon_url', sa.String(length=256), nullable=True))

    with op.batch_alter_table('plaid_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_accounts_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_finance_category', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('personal_finance_category_icon_url', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.drop_column('personal_finance_category_icon_url')
        batch_op.drop_column('personal_finance_category')

    with op.batch_alter_table('plaid_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_accounts_account_id'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('pfc_icon_url')
        batch_op.drop_column('pfc_detailed')
        batch_op.drop_column('pfc_primary')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_account_id'))

    # ### end Alembic commands ###
