"""Add parent ID CATEGORY TABLE Bish

Revision ID: 46a0ade978f9
Revises: 18b0e9bdfb29
Create Date: 2025-04-11 11:04:40.435608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a0ade978f9'
down_revision = '18b0e9bdfb29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'parent_id',
            sa.Integer(),
            sa.ForeignKey('categories.id', name='fk_categories_parent_id'),
            nullable=True
    ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
