"""Categories bullsh

Revision ID: 7665737c5164
Revises: d124119c9be4
Create Date: 2025-04-06 05:14:49.120293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7665737c5164'
down_revision = 'd124119c9be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
