name: DeepSource CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Backend: Python tests + coverage
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: |
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov deepsource

      - name: Run tests with coverage
        run: pytest --cov=backend --cov-report=xml

      - name: Report coverage to DeepSource
        run: deepsource report --analyzer test-coverage --key python --value-file backend
