name: DeepSource CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Backend: Python tests + coverage
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov deepsource
          pytest --cov=backend --cov-report xml:backend/coverage.xml

      # Frontend: Node tests + coverage
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          cd frontend
          npm ci
          npm run build --if-present
          npm run test -- --coverage --coverageReporters=lcov

      # Report coverage to DeepSource
      - name: Report coverage
        run: |
          deepsource report --analyzer test-coverage --key python --value-file backend/coverage.xml
          deepsource report --analyzer test-coverage --key javascript --value-file frontend/coverage/lcov.info
